### ISSUE TITLE
API method for total number of records in a database

### ISSUE THREAD

**Issue by lyusupov** [JulStrat/uCDB#1]
Hi Ioulianos !
Thank you so much for development of this Arduino library!

This is actually not an issue but a kind of 'feature request'.
Is there any chance to extend current API with a method that would give some sort of the database 'statistics', such as total number of records?

It looks like genuine cdb ( http://cr.yp.to/cdb/install.html ) has an example on how to implement this ( cdbstats.c  ) , right ?

   Thanks!
    Linar.

**Comment by JulStrat** [comment]
Hi, Linar!

I am planning for next release:
1. valueAvailable() - the number of `value' bytes available for reading
2. recordsNumber() - total number of records in CDB.

Regards, 
Julian.

**Comment by JulStrat** [comment]
Hi, Linar!
Just for info - I am planning uCDBMaker - simple class for creating CDB.
if you have any suggestions on uCDB API, implementation or encounter a bug, problem  
please open issue.
BTW your SoftRF project is very good.
Regards,
Julian.

**Comment by lyusupov** [comment]
Julian,

thank you for the update!

> Just for info - I am planning uCDBMaker - simple class for creating CDB.

Although I am _(personally)_ fine with the Python CDB 'maker' script provided by you - I agree that the Arduino one could make sense to create the database from CSV directly on the board.
I wish  that you would add a sketch in 'examples' area on how to make this conversion _(same as you've already done with CDB read and benchmark examples)_ .
  
> if you have any suggestions on uCDB API, implementation or encounter a bug, problem
please open issue.

I have a couple of minor suggestions for improvement  of current API - should I open a new issue or re-use this one?

    Best regards,
    Linar.

**Comment by JulStrat** [comment]
Hi, Linar.
I think it would be better if you open new issue.
