### ISSUE TITLE
transport-agnostic interface for database file access

### ISSUE THREAD

**Issue by lyusupov** [JulStrat/uCDB#2]
The is a 'request for enhancement'.

1) Your uCDB.cpp has currently hard-coded  an SD card access interface:
https://github.com/JulStrat/uCDB/blob/master/src/uCDB.cpp#L35
https://github.com/JulStrat/uCDB/blob/master/src/uCDB.cpp#L38

There are also some other methods of storage access available. One of them is SPI flash memory interface.
For my use case I had to 'tweak' your code a little bit to make it running with nRF52 Arduino Core:
https://github.com/lyusupov/SoftRF/blob/master/software/firmware/source/libraries/uCDB/src/uCDB.h#L15

**My suggestion is**:
Could you make the uCDB.cpp and uCDB.h to be 'transport-agnostic' ? (**say, by employment of "File *" access only**) and transfer the 'transport layer' _(SD - in your case)_ on the Arduino  sketch level ?
 
2) And there is one more minor notice:
I can see that you don't test **cdb** value before executing the **cdb.close**()
here: https://github.com/JulStrat/uCDB/blob/master/src/uCDB.cpp#L33
and there: https://github.com/JulStrat/uCDB/blob/master/src/uCDB.cpp#L238

Should we add some 'safety guards' like these ones ?
https://github.com/lyusupov/SoftRF/blob/master/software/firmware/source/libraries/uCDB/src/uCDB.cpp#L30
https://github.com/lyusupov/SoftRF/blob/master/software/firmware/source/libraries/uCDB/src/uCDB.cpp#L228

**Comment by JulStrat** [comment]
> make the uCDB.cpp and uCDB.h to be 'transport-agnostic'

Good enhancement :+1: Agree 

> test cdb value before executing the cdb.close()

Makes sense. I will add check.

Thank you, Linar.

**Comment by JulStrat** [comment]
Hi, Linar.
Here is my template based solution - https://github.com/JulStrat/uCDB/blob/template/src/uCDB.hpp
`airports` example uses standard `SD` library and `benchmark` - `SdFat` library.
Usage (for `SdFat`) - 
```
...
#include "SdFat.h"
#include "uCDB.hpp"
...
SdFat fat;
uCDB<SdFat, File> ucdb(fat);
...
```
And for `Adafruit_SPIFlash` it would be something like this
```
...
#include <Adafruit_SPIFlash.h>
#include "uCDB.hpp"
...
FatFileSystem fatfs;
uCDB<FatFileSystem, File> ucdb(fatfs);
...
```
Is it good, acceptable approach?
Please, advice.

Regards,
Julian.

**Comment by lyusupov** [comment]
> Is it good, acceptable approach?

Yes. It works pretty much good for me.
Thank you so much, Julian!
